---
- name: Instalar y Configurar HAProxy + Keepalived para Kubernetes API Load Balancing
  hosts: haproxy_keepalived
  become: true
  vars:
    haproxy_config_dir: "/etc/haproxy"
    keepalived_config_dir: "/etc/keepalived"
    haproxy_config_template: "../../templates/haproxy/haproxy.cfg.j2"
    keepalived_config_template: "../../templates/keepalived/keepalived.conf.j2"
    haproxy_socket_dir: "/var/lib/haproxy"
    api_vip: "10.17.5.10"  # Asegúrate de tener esta variable configurada con la IP VIP

  tasks:
    # Paso 1: Eliminar la IP estática de la interfaz eth0 si está configurada
    - name: Eliminar IP estática de la interfaz eth0
      command: ip addr del {{ api_vip }}/32 dev eth0
      when: api_vip in ansible_default_ipv4.address

    # Paso 2: Instalar net-tools para usar netstat
    - name: Instalar net-tools para usar netstat
      yum:
        name: net-tools
        state: present

    # Paso 3: Asegurar que el grupo haproxy existe
    - name: Asegurar que el grupo haproxy existe
      group:
        name: haproxy
        state: present

    # Paso 4: Asegurar que el usuario haproxy existe
    - name: Asegurar que el usuario haproxy existe
      user:
        name: haproxy
        group: haproxy
        shell: /sbin/nologin
        system: yes
        create_home: no
        state: present

    # Paso 5: Crear directorio para los sockets de HAProxy si no existe
    - name: Crear {{ haproxy_socket_dir }} si no existe y aplicar permisos
      file:
        path: "{{ haproxy_socket_dir }}"
        state: directory
        owner: haproxy
        group: haproxy
        mode: '0755'

    # Paso 6: Establecer contexto SELinux para {{ haproxy_socket_dir }}
    - name: Establecer contexto SELinux para {{ haproxy_socket_dir }}
      sefcontext:
        target: '{{ haproxy_socket_dir }}(/.*)?'
        setype: var_run_t
        state: present
      when: ansible_selinux.status == "enabled"
      ignore_errors: true

    # Paso 7: Restaurar contexto SELinux en {{ haproxy_socket_dir }}
    - name: Restaurar contexto SELinux en {{ haproxy_socket_dir }}
      command: restorecon -Rv {{ haproxy_socket_dir }}
      when: ansible_selinux.status == "enabled"
      ignore_errors: true

    # Paso 8: Eliminar socket anterior si existe
    - name: Eliminar socket anterior si existe
      file:
        path: "{{ haproxy_socket_dir }}/admin.sock"
        state: absent

    # Paso 9: Verificar si el API Server (VIP) responde en el puerto 6443
    - name: Verificar si el API Server (VIP) responde en el puerto 6443
      wait_for:
        host: "{{ api_vip }}"
        port: 6443
        timeout: 3
      register: api_server_status
      ignore_errors: yes

    # Paso 10: Definir si se habilita 'check' en HAProxy
    - name: Definir si se habilita 'check' en HAProxy
      set_fact:
        enable_api_check: "{{ api_server_status is not failed }}"

    # Paso 11: Instalar HAProxy y Keepalived
    - name: Instalar HAProxy y Keepalived
      package:
        name:
          - haproxy
          - keepalived
        state: present

    # Paso 12: Obtener interfaz activa para Keepalived
    - name: Obtener interfaz activa para Keepalived
      command: ip route get 8.8.8.8
      register: default_route

    # Paso 13: Definir interfaz para Keepalived
    - name: Definir interfaz para Keepalived
      set_fact:
        keepalived_interface: "{{ default_route.stdout.split('dev')[1].split()[0] }}"

    # Paso 14: Asegurar que el directorio de configuración de HAProxy existe
    - name: Asegurar que el directorio de configuración de HAProxy existe
      file:
        path: "{{ haproxy_config_dir }}"
        state: directory
        mode: "0755"

    # Paso 15: Copiar configuración de HAProxy
    - name: Copiar configuración de HAProxy
      template:
        src: "{{ haproxy_config_template }}"
        dest: "{{ haproxy_config_dir }}/haproxy.cfg"
        owner: root
        group: root
        mode: "0644"
      notify: Reiniciar HAProxy

    # Paso 16: Asegurar que el directorio de configuración de Keepalived existe
    - name: Asegurar que el directorio de configuración de Keepalived existe
      file:
        path: "{{ keepalived_config_dir }}"
        state: directory
        mode: "0755"

    # Paso 17: Copiar configuración de Keepalived
    - name: Copiar configuración de Keepalived
      template:
        src: "{{ keepalived_config_template }}"
        dest: "{{ keepalived_config_dir }}/keepalived.conf"
        owner: root
        group: root
        mode: "0644"
      notify: Reiniciar Keepalived

    # Paso 18: Validar configuración de HAProxy
    - name: Validar configuración de HAProxy
      command: haproxy -c -f /etc/haproxy/haproxy.cfg
      register: haproxy_check
      changed_when: false
      failed_when: haproxy_check.rc != 0

    # Paso 19: Permitir a HAProxy usar cualquier puerto TCP con SELinux (si aplica)
    - name: Permitir a HAProxy usar cualquier puerto TCP con SELinux (si aplica)
      command: setsebool -P haproxy_connect_any 1
      when: ansible_selinux.status == "enabled"
      ignore_errors: true

    # Paso 20: Modificar archivo del servicio HAProxy para agregar Sleep=5
    - name: Modificar archivo del servicio HAProxy para agregar Sleep=5
      lineinfile:
        path: /usr/lib/systemd/system/haproxy.service
        regexp: '^ExecStart='
        line: 'ExecStart=/usr/sbin/haproxy -Ws -f $CONFIG -f $CFGDIR -p $PIDFILE $OPTIONS'
        backrefs: yes
        insertbefore: '^ExecReload='

    # Paso 21: Recargar configuración de systemd
    - name: Recargar configuración de systemd
      command: systemctl daemon-reload

    # Paso 22: Esperar la disponibilidad de la IP VIP y Reiniciar el servicio HAProxy y Keepalived
    - name: Esperar que la IP VIP esté disponible en el puerto 6443 antes de reiniciar HAProxy
      wait_for:
        host: "{{ api_vip }}"
        port: 6443
        state: started
        timeout: 30

    - name: Reiniciar el servicio HAProxy y Keepalived
      systemd:
        name: "{{ item }}"
        state: restarted
        enabled: true
      loop:
        - keepalived
        - haproxy

    # Paso 23: Abrir puerto 6443 en el firewall
    - name: Abrir puerto 6443 en el firewall
      firewalld:
        port: 6443/tcp
        permanent: true
        state: enabled
      notify: Recargar firewall

  handlers:
    - name: Reiniciar HAProxy
      systemd:
        name: haproxy
        state: restarted

    - name: Reiniciar Keepalived
      systemd:
        name: keepalived
        state: restarted

    - name: Recargar firewall
      command: firewall-cmd --reload