# ansible/playbooks/install_haproxy_keepalived.yml
- name: Instalar y Configurar HAProxy + Keepalived para Kubernetes API e Ingress
  hosts: haproxy_keepalived
  become: true
  vars:
    haproxy_config_dir: "/etc/haproxy"
    keepalived_config_dir: "/etc/keepalived"
    haproxy_config_template: "../../templates/haproxy/haproxy.cfg.j2"
    keepalived_config_template: "../../templates/keepalived/keepalived.conf.j2"
    haproxy_socket_dir: "/var/lib/haproxy"
    haproxy_socket_file: "/var/lib/haproxy/admin.sock"
    api_vip: "10.17.5.10"
    second_vip: "10.17.5.30"

  tasks:
    - name: Limpiar la caché de DNF
      command: dnf clean all
      changed_when: false

    - name: Actualizar paquetes del sistema
      command: dnf update -y
      changed_when: false

    - name: Verificar conectividad a internet
      command: ping -c 3 8.8.8.8
      register: ping_output
      failed_when: ping_output.rc != 0
      ignore_errors: true
      changed_when: false

    - name: Verificar disponibilidad de repositorios
      command: dnf repolist
      register: repo_status
      failed_when: repo_status.rc != 0
      ignore_errors: true
      changed_when: false

    - name: Instalar paquetes requeridos
      yum:
        name:
          - net-tools
          - haproxy
          - keepalived
          - python3-dnf
          - libselinux-python3
        state: present

    - name: Crear grupo haproxy si no existe
      group:
        name: haproxy
        state: present

    - name: Crear usuario haproxy si no existe
      user:
        name: haproxy
        group: haproxy
        shell: /sbin/nologin
        system: yes
        create_home: no
        state: present

    - name: Crear directorio para el socket de HAProxy
      file:
        path: "{{ haproxy_socket_dir }}"
        state: directory
        owner: haproxy
        group: haproxy
        mode: "0750"

    - name: Habilitar bind a IPs no locales
      ansible.posix.sysctl:
        name: net.ipv4.ip_nonlocal_bind
        value: "1"
        sysctl_file: /etc/sysctl.d/99-haproxy-nonlocal-bind.conf
        reload: yes
        state: present
      notify: Reiniciar Keepalived

    - name: Restaurar contexto SELinux para socket
      command: restorecon -RFv {{ haproxy_socket_dir }}
      when: ansible_selinux.status == "enabled"
      ignore_errors: true
      changed_when: false

    - name: Establecer contexto SELinux para el socket
      sefcontext:
        target: "{{ haproxy_socket_dir }}(/.*)?"
        setype: var_run_t
        state: present
      when: ansible_selinux.status == "enabled"

    - name: Permitir a HAProxy conectarse a cualquier puerto
      seboolean:
        name: haproxy_connect_any
        state: true
        persistent: true
      when: ansible_selinux.status == "enabled"

    - name: Detener HAProxy si está activo
      systemd:
        name: haproxy
        state: stopped
      ignore_errors: true
      changed_when: false

    - name: Eliminar socket anterior de HAProxy
      file:
        path: "{{ haproxy_socket_file }}"
        state: absent

    - name: Crear directorio override systemd para HAProxy
      file:
        path: /etc/systemd/system/haproxy.service.d
        state: directory
        mode: "0755"

    - name: Crear sobreescritura systemd para HAProxy
      copy:
        dest: /etc/systemd/system/haproxy.service.d/override.conf
        content: |
          [Service]
          ExecStart=
          ExecStart=/usr/sbin/haproxy -Ws -f /etc/haproxy/haproxy.cfg
          RuntimeDirectory=haproxy
          RuntimeDirectoryMode=0750
          User=haproxy
          Group=haproxy
          AmbientCapabilities=CAP_NET_BIND_SERVICE
          CapabilityBoundingSet=CAP_NET_BIND_SERVICE
          PrivateTmp=true
          ProtectSystem=full
          NoNewPrivileges=true
      notify: Recargar systemd daemon

    - name: Crear directorio de configuración de HAProxy
      file:
        path: "{{ haproxy_config_dir }}"
        state: directory
        mode: "0755"

    - name: Crear directorio de configuración de Keepalived
      file:
        path: "{{ keepalived_config_dir }}"
        state: directory
        mode: "0755"

    - name: Detectar interfaz activa para Keepalived
      command: ip route get 8.8.8.8
      register: default_route

    - name: Definir interfaz para Keepalived
      set_fact:
        keepalived_interface: "{{ default_route.stdout.split('dev')[1].split()[0] }}"

    - name: Mostrar interfaz detectada
      debug:
        msg: "Interfaz usada por Keepalived en {{ inventory_hostname }}: {{ keepalived_interface }}"

    - name: Configurar Keepalived
      template:
        src: "{{ keepalived_config_template }}"
        dest: "{{ keepalived_config_dir }}/keepalived.conf"
        owner: root
        group: root
        mode: "0644"
      notify: Reiniciar Keepalived

    - name: Configurar HAProxy
      template:
        src: "{{ haproxy_config_template }}"
        dest: "{{ haproxy_config_dir }}/haproxy.cfg"
        owner: root
        group: root
        mode: "0644"
      notify: Validar y reiniciar HAProxy

    - name: Habilitar y arrancar Keepalived
      systemd:
        name: keepalived
        enabled: true
        state: started

    - name: Habilitar e iniciar HAProxy (con soporte a IPs no locales)
      systemd:
        name: haproxy
        enabled: true
        state: started

  handlers:
    - name: Recargar systemd daemon
      listen: Recargar systemd daemon
      systemd:
        daemon_reload: true

    - name: Reiniciar Keepalived
      listen: Reiniciar Keepalived
      systemd:
        name: keepalived
        state: restarted

    - name: Validar y reiniciar HAProxy
      listen: Validar y reiniciar HAProxy
      block:
        - name: Validar configuración HAProxy
          command: haproxy -c -f /etc/haproxy/haproxy.cfg
          register: haproxy_config_check
          changed_when: false

        - name: Reiniciar HAProxy si la validación fue exitosa
          systemd:
            name: haproxy
            state: restarted
          when: haproxy_config_check.rc == 0